# Site settings
title: "méline querré"
description: ""
baseurl: ""
url: "https://mwanheda.github.io"  # absolute url

# Build settings
include: ["_pages"]  # include more files
kramdown:
  input: GFM
