# Site settings
title: "Méline Querré"
description: "Portfolio de Méline Querré"
baseurl: ""
url: "https://mwanheda.github.io"

# Build settings
include:
  - _pages
  - _base.scss
  - _videos.scss
  - _header.scss
  - _nav.scss
kramdown:
  input: GFM
